
DELETE  http://localhost:9000/api/questions/62accd4f405d584e72ed1c75 HTTP/1.1
###


GET   http://localhost:9000/api/questions/ HTTP/1.1
###


GET  http://localhost:9000/api/questions/62adfa56baf244e787758cf1 HTTP/1.1
###
GET  http://localhost:9000/api/questions/?search=va HTTP/1.1
###

DELETE   http://localhost:9000/api/questions/62acc9832676e14a5dcf46da HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9yZ2FuaXphdGlvbkBnbWFpbC5jb20iLCJfaWQiOiI2MjBiN2VhNGNjYWVkMTllOTk3ZTc5NTciLCJwcml2aWxlZ2UiOlsiaXNPcmdhbml6YXRpb24iXSwiaWF0IjoxNjQ1MDAxMjIzfQ.-0IqbQenYRbO2dGAOE61BDmcQHnWUCt--M9InvUOvKM

{

 "text": "wagon rh lkjwewe"
}
###
POST http://localhost:9000/api/questions HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9yZ2FuaXphdGlvbkBnbWFpbC5jb20iLCJfaWQiOiI2MjBiN2VhNGNjYWVkMTllOTk3ZTc5NTciLCJwcml2aWxlZ2UiOlsiaXNPcmdhbml6YXRpb24iXSwiaWF0IjoxNjQ1MDAxMjIzfQ.-0IqbQenYRbO2dGAOE61BDmcQHnWUCt--M9InvUOvKM

{

 "text": "wait fiath two"
}

